/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ADatePicker: typeof import('ant-design-vue/es')['DatePicker']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    AsideMenu: typeof import('./components/aside-menu/index.vue')['default']
    ASpace: typeof import('ant-design-vue/es')['Space']
    GlobalOutlined: typeof import('@ant-design/icons-vue')['GlobalOutlined']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    HomeOutlined: typeof import('@ant-design/icons-vue')['HomeOutlined']
    Logo: typeof import('./components/logo/index.vue')['default']
    MenuFoldOutlined: typeof import('@ant-design/icons-vue')['MenuFoldOutlined']
    MenuUnfoldOutlined: typeof import('@ant-design/icons-vue')['MenuUnfoldOutlined']
    Nav: typeof import('./components/nav/index.vue')['default']
    NotificationOutlined: typeof import('@ant-design/icons-vue')['NotificationOutlined']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    TopNav: typeof import('./components/top-nav/index.vue')['default']
    UploadOutlined: typeof import('@ant-design/icons-vue')['UploadOutlined']
    UserOutlined: typeof import('@ant-design/icons-vue')['UserOutlined']
    VideoCameraOutlined: typeof import('@ant-design/icons-vue')['VideoCameraOutlined']
  }
}
